name: CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push Backend
      uses: docker/build-push-action@v4
      with:
        context: ./backend
        push: true
        tags: ${{ secrets.DOCKER_REGISTRY }}/hello-world-backend:latest

    - name: Build and push Frontend
      uses: docker/build-push-action@v4
      with:
        context: ./frontend
        push: true
        tags: ${{ secrets.DOCKER_REGISTRY }}/hello-world-frontend:latest

    - name: Install kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Configure kubectl
      run: |
        echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig.yaml
        export KUBECONFIG=kubeconfig.yaml

    - name: Deploy to Kubernetes
      run: |
        # Update image names in Kubernetes manifests
        sed -i "s|hello-world-backend:latest|${{ secrets.DOCKER_REGISTRY }}/hello-world-backend:latest|g" k8s/backend-deployment.yaml
        sed -i "s|hello-world-frontend:latest|${{ secrets.DOCKER_REGISTRY }}/hello-world-frontend:latest|g" k8s/frontend-deployment.yaml
        
        # Apply Kubernetes manifests
        kubectl apply -f k8s/backend-deployment.yaml
        kubectl apply -f k8s/backend-service.yaml
        kubectl apply -f k8s/frontend-deployment.yaml
        kubectl apply -f k8s/frontend-service.yaml
        
        # Wait for deployments to be ready
        kubectl rollout status deployment/backend
        kubectl rollout status deployment/frontend

    # Add your deployment steps here
    # For example, deploying to a cloud provider
    # - name: Deploy to Production
    #   run: |
    #     echo "Add your deployment commands here" 